openapi: 3.0.1
info:
  title: Well-Known
  description: Well-Known
  version: 1.0.0
servers:
  - url: https://${hostname}/.well-known
paths:
  /jwks.json:
    get:
      tags:
        - wellKnown
      operationId: jwks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
